version: "3.9"

services:
  mariadb:
    container_name: "mariadb"
    build: ./requirements/mariadb/
    restart: on-failure
    env_file:
      - .env
    volumes:
      - DB:/var/run/mysql
    networks:
      - my-network
  
  wordpress:
    container_name: "wordpress"
    build: ./requirements/wp/
    restart: on-failure
    depends_on: 
      - mariadb
    networks:
      - my-network
    volumes:
      - wp:/var/www/html
    env_file:
      - .env

  nginx:
    container_name: "nginx"
    build: ./requirements/nginx/
    restart: on-failure
    depends_on: 
      - wordpress
    ports:
      - "443:443"
    networks: 
      - my-network
    volumes:
      - wp:/var/www/html 

volumes:
  DB:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: /home/fatimzehra/data/DB
  wp:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: /home/fatimzehra/data/wp


networks:
  my-network:
# fpm(protocol to generate port li ghaydwi fih nginx m3a wp)
