version: "3.9"

services:
  mariaDB:
    image: "mariadb"
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: databasename
      MYSQL_USER: fael-bou
      MYSQL_PASSWORD: 123456
      MYSQL_HOSTNAME: fael-bou.42.fr
    volumes:
      - DB:/var/lib/mysql
    networks:
      - my-network
  
  wordpress:
    container_name: "wordpress"
    build: ./requirements/wp/
    restart: on-failure
    depends_on: 
      - mariaDB
    ports:
      - "9000:9000"
    networks:
      - my-network
    volumes:
      - wp:/var/www/html
    env_file:
      - .env

  nginx:
    container_name: "nginx"
    build: ./requirements/nginx/
    restart: on-failure
    depends_on: 
      - wordpress
    ports:
      - "443:443"
    networks: 
      - my-network
    volumes:
      - wp:/var/www/html 

volumes:
  DB:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: /home/fatimzehra/data/DB
  wp:
    driver: local
    driver_opts:
      type: 'none'
      o: bind
      device: /home/fatimzehra/data/wp


networks:
  my-network:
# fpm(protocol to generate port li ghaydwi fih nginx m3a wp)
