FROM debian:bullseye


RUN apt-get -y update \
	&& apt-get -y upgrade \
	&& apt-get -y install nginx

RUN apt-get -y install curl net-tools

COPY ./nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /var/www/html && \
	chmod -R 755 /var/www/html

COPY ./index.html /var/www/html

CMD ["nginx"]
