FROM debian:bullseye

WORKDIR /var/www/html/

COPY ./script.sh .

RUN chmod +x /var/www/html/script.sh

RUN apt-get -y update \
	&& apt-get -y upgrade


COPY ./index.php /var/www/html

#fpm should connect to nginx by port 9000 (add them to same network)
#copy wp and fpm config files

RUN apt-get install -y wget

RUN apt-get install -y php-fpm php-mysql 
#RUN mkdir -p /run/php/;
#RUN touch /run/php/php-fpm.pid;
#RUN sed -i "s/listen = \/run\/php\/php-fpm.sock/listen = 9000/" "/etc/php/fpm/pool.d/www.conf"
#Store PID files for PHP processes managed by the PHP-FPM

ENTRYPOINT ["sh", "script.sh"]
